---
title: "[CDISC] CDISC ADaM Clinical Trial Analysis"
author: "SEOYEON CHOI"
date: "2026-03-03"
---

# ADaM Analysis Data Model

> The **ADaM (Analysis Data Model)** dataset is a CDISC standard for organizing clinical trial data to support statistical analysis, regulatory reporting, and traceability. Derived from **SDTM (Study Data Tabulation Model)** data, ADaM datasets are designed to be **"analysis-ready"** for generating tables, listings, and figures. They are required by **regulatory agencies like the FDA and PMDA**.

# Reference

- [Phase II Alzheimer’s clinical trial Data](https://github.com/cdisc-org/sdtm-adam-pilot-project/tree/master)
    - [adamdata guide](https://github.com/cdisc-org/sdtm-adam-pilot-project/blob/master/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/analysis/adam/datasets/dataguide.pdf)
- [Explanation](https://www.lexjansen.com/pharmasug/2012/DS/PharmaSUG-2012-DS18.pdf)

**Methodology**

> This was a prospective, randomized, multi-center, double-blind, placebo-controlled,
parallel-group study. Subjects were randomized equally to placebo, xanomeline low
dose, or xanomeline

**Study Overview**

- Study design: 
    - Phase II randomized clinical trial
    - 3 treatment arms (Placebo / Low dose / High dose)
    - Duration: 26 weeks
    - Population: Mild–moderate Alzheimer’s disease patients
- Primary objectives
    - Evaluate efficacy of active drug vs placebo
    - Assess safety and tolerability
- Endpoints
    - Primary efficacy:
        - ADAS-Cog score
    - Secondary:
        - CIBIC+
        - NPI
    - Safety
        - Adverse events
        - Laboratory tests
        - Vital signs

# Import

In [1]:
import pandas as pd
import pyreadstat
import os
from pathlib import Path

# Data

In [2]:
data_folder = Path("../../../../delete/adam/")

In [3]:
files = [
    "adae.xpt",
    "adlbc.xpt",
    "adlbh.xpt",
    "adlbhy.xpt",
    "adqsadas.xpt",
    "adqscibc.xpt",
    "adqsnpix.xpt",
    "adsl.xpt",
    "adtte.xpt",
    "advs.xpt"
]

In [4]:
data = {}
metadata = {}

In [5]:
for f in files:
    full_path = data_folder / f
    df, meta = pyreadstat.read_xport(full_path)
    
    key = f.replace(".xpt","")
    
    data[key] = df
    metadata[key] = meta
    
    print(f"{f} loaded:", df.shape)

adae.xpt loaded: (1191, 55)
adlbc.xpt loaded: (74264, 46)
adlbh.xpt loaded: (49932, 46)
adlbhy.xpt loaded: (9954, 43)
adqsadas.xpt loaded: (12463, 40)
adqscibc.xpt loaded: (730, 36)
adqsnpix.xpt loaded: (31140, 41)
adsl.xpt loaded: (254, 48)
adtte.xpt loaded: (254, 26)
advs.xpt loaded: (32139, 34)

## ADSL

> The first is ADSL (Subject Level Analysis Dataset), a one-recordper-subject structure that contains subject-level attributes. Because of its structure, it can be merged onto any other clinical dataset, including other ADaM datasets and SDTM datasets.

In [6]:
data['adsl'].head()

,STUDYID,USUBJID,SUBJID,SITEID,SITEGR1,ARM,TRT01P,TRT01PN,TRT01A,TRT01AN,...,DURDIS,DURDSGR1,VISIT1DT,RFSTDTC,RFENDTC,VISNUMEN,RFENDT,DCDECOD,DCREASCD,MMSETOT
0,CDISCPILOT01,01-701-1015,1015,701,701,Placebo,Placebo,0.0,Placebo,0.0,...,43.9,>=12,2013-12-26,2014-01-02,2014-07-02,12.0,2014-07-02,COMPLETED,Completed,23.0
1,CDISCPILOT01,01-701-1023,1023,701,701,Placebo,Placebo,0.0,Placebo,0.0,...,76.4,>=12,2012-07-22,2012-08-05,2012-09-02,5.0,2012-09-02,ADVERSE EVENT,Adverse Event,23.0
2,CDISCPILOT01,01-701-1028,1028,701,701,Xanomeline High Dose,Xanomeline High Dose,81.0,Xanomeline High Dose,81.0,...,42.8,>=12,2013-07-11,2013-07-19,2014-01-14,12.0,2014-01-14,COMPLETED,Completed,23.0
3,CDISCPILOT01,01-701-1033,1033,701,701,Xanomeline Low Dose,Xanomeline Low Dose,54.0,Xanomeline Low Dose,54.0,...,55.3,>=12,2014-03-10,2014-03-18,2014-04-14,5.0,2014-04-14,STUDY TERMINATED BY SPONSOR,Sponsor Decision,23.0
4,CDISCPILOT01,01-701-1034,1034,701,701,Xanomeline High Dose,Xanomeline High Dose,81.0,Xanomeline High Dose,81.0,...,32.9,>=12,2014-06-24,2014-07-01,2014-12-30,12.0,2014-12-30,COMPLETED,Completed,21.0

In [7]:
metadata['adsl'].column_names_to_labels

{'STUDYID': 'Study Identifier',
 'USUBJID': 'Unique Subject Identifier',
 'SUBJID': 'Subject Identifier for the Study',
 'SITEID': 'Study Site Identifier',
 'SITEGR1': 'Pooled Site Group 1',
 'ARM': 'Description of Planned Arm',
 'TRT01P': 'Planned Treatment for Period 01',
 'TRT01PN': 'Planned Treatment for Period 01 (N)',
 'TRT01A': 'Actual Treatment for Period 01',
 'TRT01AN': 'Actual Treatment for Period 01 (N)',
 'TRTSDT': 'Date of First Exposure to Treatment',
 'TRTEDT': 'Date of Last Exposure to Treatment',
 'TRTDUR': 'Duration of Treatment (days)',
 'AVGDD': 'Avg Daily Dose (as planned)',
 'CUMDOSE': 'Cumulative Dose (as planned)',
 'AGE': 'Age',
 'AGEGR1': 'Pooled Age Group 1',
 'AGEGR1N': 'Pooled Age Group 1 (N)',
 'AGEU': 'Age Units',
 'RACE': 'Race',
 'RACEN': 'Race (N)',
 'SEX': 'Sex',
 'ETHNIC': 'Ethnicity',
 'SAFFL': 'Safety Population Flag',
 'ITTFL': 'Intent-To-Treat Population Flag',
 'EFFFL': 'Efficacy Population Flag',
 'COMP8FL': 'Completers of Week 8 Population Flag',
 'COMP16FL': 'Completers of Week 16 Population Flag',
 'COMP24FL': 'Completers of Week 24 Population Flag',
 'DISCONFL': 'Did the Subject Discontinue the Study?',
 'DSRAEFL': 'Discontinued due to AE?',
 'DTHFL': 'Subject Died?',
 'BMIBL': 'Baseline BMI (kg/m^2)',
 'BMIBLGR1': 'Pooled Baseline BMI Group 1',
 'HEIGHTBL': 'Baseline Height (cm)',
 'WEIGHTBL': 'Baseline Weight (kg)',
 'EDUCLVL': 'Years of Education',
 'DISONSDT': 'Date of Onset of Disease',
 'DURDIS': 'Duration of Disease (Months)',
 'DURDSGR1': 'Pooled Disease Duration Group 1',
 'VISIT1DT': 'Date of Visit 1',
 'RFSTDTC': 'Subject Reference Start Date/Time',
 'RFENDTC': 'Subject Reference End Date/Time',
 'VISNUMEN': 'End of Trt Visit (Vis 12 or Early Term.)',
 'RFENDT': 'Date of Discontinuation/Completion',
 'DCDECOD': 'Standardized Disposition Term',
 'DCREASCD': 'Reason for Discontinuation',
 'MMSETOT': 'MMSE Total'}

# Table

## Table 11-1. Demographic Characteristics

In [289]:
data2 = data['adsl'].copy()

data2['RACE2'] = data2['RACE'].replace({
    'WHITE': 'White/Caucasian',
    'BLACK OR AFRICAN AMERICAN': 'Other',
    'AMERICAN INDIAN OR ALASKA NATIVE': 'Other'
})

In [290]:
n_counts = data['adsl'].groupby('ARM')['USUBJID'].nunique()
total_n = data['adsl']['USUBJID'].nunique()
n_counts['Total'] = total_n

In [316]:
def mean_min_max_table(df, var, group_col='ARM', total_label='Total',
                       mean_digits=1, minmax_digits=0):

    arm_summary = (
        df.groupby(group_col)[var]
          .agg(['mean', 'min', 'max'])
    )

    total_summary = (
        df[var]
          .agg(['mean', 'min', 'max'])
          .to_frame().T
    )
    total_summary.index = [total_label]

    final = pd.concat([arm_summary, total_summary])

    final[f'{var} Mean (Min–Max)'] = (
        final['mean'].round(mean_digits).astype(str)
        + " ("
        + final['min'].round(minmax_digits).astype(int).astype(str)
        + "–"
        + final['max'].round(minmax_digits).astype(int).astype(str)
        + ")"
    )

    return final[[f'{var} Mean (Min–Max)']]

In [ ]:
def categorical_table(df, var, group_col='ARM', total_label='Total', pct_digits=0):

    ct = pd.crosstab(df[var], df[group_col])

    pct = ct.div(ct.sum(axis=0), axis=1) * 100

    formatted = (
        ct.astype(str) + " (" +
        pct.round(pct_digits).astype(int).astype(str) + "%)"
    )

    total_n = df.shape[0]
    total_ct = df[var].value_counts()
    total_pct = total_ct / total_n * 100

    formatted[total_label] = (
        total_ct.astype(str) + " (" +
        total_pct.round(pct_digits).astype(int).astype(str) + "%)"
    )

    formatted.columns.name = None

    return formatted

In [313]:
Table11_1 = pd.concat([mean_min_max_table(data['adsl'],'AGE').T,
                    categorical_table(data['adsl'],'SEX').reset_index().set_index('SEX').reindex(['M', 'F']),
                    categorical_table(data2,'RACE2').reset_index().set_index('RACE2').reindex(['White/Caucasian', 'Other']),
                    mean_min_max_table(data['adsl'],'EDUCLVL').T,
                   ])

In [314]:
Table11_1.columns = [
    f"{col} (n={n_counts[col]})" if col in n_counts.index
    else col
    for col in final2.columns
]

In [315]:
Table11_1

,Placebo (n=86),Xanomeline High Dose (n=84),Xanomeline Low Dose (n=84),Total (n=254)
AGE Mean (Min–Max),75.2 (52–89),74.4 (56–88),75.7 (51–88),75.1 (51–89)
M,33 (38%),44 (52%),34 (40%),111 (44%)
F,53 (62%),40 (48%),50 (60%),143 (56%)
White/Caucasian,78 (91%),74 (88%),78 (93%),230 (91%)
Other,8 (9%),10 (12%),6 (7%),24 (9%)
EDUCLVL Mean (Min–Max),12.6 (6–21),12.5 (6–20),13.2 (3–24),12.8 (3–24)

In [319]:
data['adtte']

,STUDYID,SITEID,USUBJID,AGE,AGEGR1,AGEGR1N,RACE,RACEN,SEX,TRTSDT,...,PARAMCD,AVAL,STARTDT,ADT,CNSR,EVNTDESC,SRCDOM,SRCVAR,SRCSEQ,SAFFL
0,CDISCPILOT01,701,01-701-1015,63.0,<65,1.0,WHITE,1.0,F,2014-01-02,...,TTDE,2.0,2014-01-02,2014-01-03,0.0,Dematologic Event Occured,ADAE,ASTDT,1.0,Y
1,CDISCPILOT01,701,01-701-1023,64.0,<65,1.0,WHITE,1.0,M,2012-08-05,...,TTDE,3.0,2012-08-05,2012-08-07,0.0,Dematologic Event Occured,ADAE,ASTDT,1.0,Y
2,CDISCPILOT01,701,01-701-1028,71.0,65-80,2.0,WHITE,1.0,M,2013-07-19,...,TTDE,3.0,2013-07-19,2013-07-21,0.0,Dematologic Event Occured,ADAE,ASTDT,1.0,Y
3,CDISCPILOT01,701,01-701-1033,74.0,65-80,2.0,WHITE,1.0,M,2014-03-18,...,TTDE,28.0,2014-03-18,2014-04-14,1.0,Study Completion Date,ADSL,RFENDT,NaN,Y
4,CDISCPILOT01,701,01-701-1034,77.0,65-80,2.0,WHITE,1.0,F,2014-07-01,...,TTDE,58.0,2014-07-01,2014-08-27,0.0,Dematologic Event Occured,ADAE,ASTDT,1.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,CDISCPILOT01,718,01-718-1254,78.0,65-80,2.0,WHITE,1.0,M,2013-07-10,...,TTDE,35.0,2013-07-10,2013-08-13,0.0,Dematologic Event Occured,ADAE,ASTDT,4.0,Y
250,CDISCPILOT01,718,01-718-1328,86.0,>80,3.0,WHITE,1.0,M,2013-02-01,...,TTDE,51.0,2013-02-01,2013-03-23,0.0,Dematologic Event Occured,ADAE,ASTDT,1.0,Y
251,CDISCPILOT01,718,01-718-1355,79.0,65-80,2.0,WHITE,1.0,M,2013-02-28,...,TTDE,9.0,2013-02-28,2013-03-08,0.0,Dematologic Event Occured,ADAE,ASTDT,1.0,Y
252,CDISCPILOT01,718,01-718-1371,69.0,65-80,2.0,WHITE,1.0,F,2013-04-26,...,TTDE,29.0,2013-04-26,2013-05-24,0.0,Dematologic Event Occured,ADAE,ASTDT,3.0,Y
253,CDISCPILOT01,718,01-718-1427,74.0,65-80,2.0,BLACK OR AFRICAN AMERICAN,2.0,F,2012-12-17,...,TTDE,42.0,2012-12-17,2013-01-27,0.0,Dematologic Event Occured,ADAE,ASTDT,9.0,Y